trigger:
  branches:
    include:
      - refs/heads/master

jobs:
  - job: Phase_1
    displayName: Build and analyze Python code
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: ubuntu-20.04
    steps:
      - checkout: self

      - task: SonarQubePrepare@4
        inputs:
          SonarQube: http://sonarqube-teste-cloudhub.azurewebsites.net/
          projectKey: ckp-teste-cloudhub
          projectName: ckp teste cloudhub
          projectVersion: 2023-09-10

      - task: RestorePythonPackages@2
        inputs:
          version: 3.9

      - task: BuildPython@2
        inputs:
          script: main.py

      - task: SonarQubeAnalyze@4
        inputs:
          sonarcloud: sonarcloud.io
          organization: https://dev.azure.com/RM92952/

      - task: SonarQubePublish@4
        inputs:
          sonarcloud: sonarcloud.io
          organization: https://dev.azure.com/RM92952/
          qualityGates:
            - gateId: "SonarQube Quality Gate"
              status: "OK"
