trigger:
  branches:
    include:
    - refs/heads/master
name: $(date:yyyyMMdd)$(rev:.rr)
jobs:
- job: Phase_1
  displayName: Build Push Image
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: SonarQubePrepare@4
    displayName: Prepare analysis on SonarQube
    inputs:
      SonarQube: teste
      projectKey: ckp-teste-cloudhub
      projectName: ckp teste cloudhub
  - task: NuGetRestore@2
    displayName: Restore NuGet packages
    inputs:
      version: 5.8
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '**/*.csproj'
  - task: SonarQubeAnalyze@4
    displayName: Run Code Analysis
  - task: SonarQubePublish@4
    displayName: Publish Quality Gate Result